//setting initial values
int round = 0;

//while loop main state


//while loop fight state
//if boss health > 0, at least one players health > 0, begin round, add 1 to round counter
while (boss.health > 0) {
	List playersHealth = new ArrayList;
	
	round ++ 1;
	
}




//RNG selects player, player cannot be chosen more than once during 1 round
Import java.util.Random;
public class selectPlayer {
public static void main(String args[ ])
{
	Random rand = new Random();
	int min = 1;
	int min = 4
	int randomNumber = rand.nextInt(max - min) + min;
	return randomNumber;
}
}

